# Generated by Django 5.1.5 on 2025-01-25 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autor", "0001_initial"),
        ("curso", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Links",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site",
                    models.CharField(max_length=100, verbose_name="Site de compra"),
                ),
                ("link", models.TextField(verbose_name="Link do site")),
            ],
            options={
                "verbose_name_plural": "Links",
            },
        ),
        migrations.CreateModel(
            name="Livros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=70)),
                ("descrição", models.TextField(blank=True, max_length=500)),
                (
                    "ano_publicacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de publicação"
                    ),
                ),
                ("editora", models.CharField(max_length=100, null=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="autor.autor"
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categoria_livro",
                        to="livros.categoria",
                        verbose_name="Categoria do livro",
                    ),
                ),
                (
                    "links",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="livros.links",
                        verbose_name="Onde comprar",
                    ),
                ),
                (
                    "materia",
                    models.ManyToManyField(
                        related_name="materia_livro",
                        to="curso.materias",
                        verbose_name="Materias associadas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livro",
                "verbose_name_plural": "Livros",
                "ordering": ["titulo"],
            },
        ),
    ]
