# Generated by Django 5.1.5 on 2025-01-25 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autor", "0001_initial"),
        ("livros", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livros",
            name="autor",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="autor.autor"
            ),
        ),
    ]
