# Generated by Django 5.1.5 on 2025-01-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0002_alter_livros_autor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livros",
            name="categoria",
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
    ]
