# Generated by Django 5.1.5 on 2025-01-26 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0003_remove_livros_categoria_delete_categoria"),
        ("usuario", "0003_alter_usuario_identificacao"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Links",
            new_name="Link",
        ),
        migrations.AlterModelOptions(
            name="link",
            options={},
        ),
        migrations.AlterField(
            model_name="livros",
            name="titulo",
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("corpo", models.TextField()),
                ("postado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="livros.livros"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuario.usuario",
                    ),
                ),
            ],
            options={
                "ordering": ["postado_em"],
            },
        ),
    ]
