# Generated by Django 5.1.5 on 2025-01-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0004_rename_links_link_alter_link_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="livros",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
