# Generated by Django 5.1.5 on 2025-01-26 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0005_livros_slug"),
        ("usuario", "0003_alter_usuario_identificacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favoritos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livro_favorito",
                        to="livros.livros",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favoritos_usuario",
                        to="usuario.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livro Favorito",
                "verbose_name_plural": "Livros Favoritos",
                "unique_together": {("livro", "usuario")},
            },
        ),
    ]
