# Generated by Django 5.1.5 on 2025-01-25 02:26

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nome_completo", models.CharField(max_length=50)),
                (
                    "ocupacao",
                    models.CharField(
                        choices=[
                            ("E", "Estudante"),
                            ("P", "Professor"),
                            ("O", "Outro"),
                        ],
                        max_length=1,
                        verbose_name="Ocupação",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de nascimento"
                    ),
                ),
                (
                    "tipo_identificacao",
                    models.CharField(
                        choices=[("M", "Matrícula"), ("C", "CPF")],
                        default="C",
                        max_length=1,
                    ),
                ),
                ("identificacao", models.IntegerField(blank=True, unique=True)),
                (
                    "genero",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
