# Generated by Django 5.1.5 on 2025-01-25 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="nome_completo",
        ),
    ]
