# Generated by Django 5.1.5 on 2025-01-25 21:10

import apps.usuario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0002_remove_usuario_nome_completo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="identificacao",
            field=models.CharField(
                blank=True,
                max_length=13,
                unique=True,
                validators=[apps.usuario.models.validate_identificacao],
            ),
        ),
    ]
