# Generated by Django 5.1.5 on 2025-01-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autor",
            name="nome",
        ),
        migrations.RemoveField(
            model_name="autor",
            name="sobrenome",
        ),
        migrations.AddField(
            model_name="autor",
            name="nome_completo",
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="autor",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
