# Generated by Django 5.1.5 on 2025-01-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Materias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=70)),
                ("fase_basica", models.BooleanField()),
                (
                    "periodo",
                    models.IntegerField(
                        choices=[
                            (1, "1° período"),
                            (2, "2° período"),
                            (3, "3° período"),
                            (4, "4° período"),
                            (5, "5° período"),
                            (6, "6° período"),
                            (7, "7° período"),
                            (8, "8° período"),
                            (9, "9° período"),
                            (10, "10° período"),
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name": "Materia",
                "verbose_name_plural": "Materias",
                "ordering": ["periodo"],
            },
        ),
        migrations.CreateModel(
            name="Cursos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("materias", models.ManyToManyField(to="curso.materias")),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
                "ordering": ["nome"],
            },
        ),
    ]
